---
- name: Enable hugepages
  hosts: all
  tasks:
    - name: Get stat info of infra_testing folder
      ansible.builtin.stat:
        path: "infra_testing/scripts/"
      register: infra_testing_stat
    - name: Assert syseng exists
      ansible.builtin.assert:
        that:
          - "infra_testing_stat.stat.exists == true"
    - name: Get stat info of nr_hugepages
      ansible.builtin.stat:
        path: "/sys/kernel/mm/hugepages/hugepages-1048576kB/nr_hugepages"
      register: nr_hugepages_stat
    - name: Assert nr_hugepages exists
      ansible.builtin.assert:
        that:
          - "nr_hugepages_stat.stat.exists == true"
    - name: Get stat info of dev/tenstorrent
      ansible.builtin.stat:
        path: "/dev/tenstorrent"
      register: tt_dev_stat
    - name: Assert devices exist
      ansible.builtin.assert:
        that:
          - "tt_dev_stat.stat.exists == true"
    - name: Copy hugepages rc to remote rc.local
      become: yes
      ansible.builtin.copy:
        src: "infra_testing/scripts/rc.local"
        dest: /etc/rc.local
        remote_src: yes
    - name: Make rc.local executable
      become: yes
      file:
        path: /etc/rc.local
        mode: u+x
    - name: Enable rc.local
      become: yes
      ansible.builtin.systemd:
        name: rc-local.service
        state: started
        daemon_reload: true
      async: 450
      poll: 5
    - name: Execute script to enable
      become: yes
      shell:
        chdir: "infra_testing/scripts/"
        cmd: "python3 setup_hugepages.py first_pass"
      environment:
        PATH: "{{ lookup('ansible.builtin.env', 'PATH', default=Undefined) }}"
      register: run_hugepages_enable_output
