name: "Ensure Active Weka Mount"
description: "Make sure weka mount is active"

inputs:
  os:
    description: 'Runner OS'
    required: true

runs:
  using: "composite"
  steps:
    - name: Ensure active weka mount
      shell: bash
      timeout-minutes: 5
      run: |
        ./.github/scripts/cloud_utils/mount_weka.sh
