# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
      args: ["--unsafe"]
    - id: check-added-large-files
# Using this mirror lets us use mypyc-compiled black, which is about 2x faster
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 23.10.1
  hooks:
    - id: black
      language_version: python3
- repo: https://github.com/BlankSpruce/gersemi
  rev: 0.16.2
  hooks:
  - id: gersemi
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.35.1
  hooks:
    - id: yamllint
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v18.1.5  # Adjust this version to match your desired clang-format version
  hooks:
    - id: clang-format
      types_or: [c++, c]
      exclude: |
        ^tests/tt_eager/ops/ccl/test_ccl_reduce_scatter_host_helpers\.cpp$
        |^tests/tt_metal/distributed/test_distributed\.cpp$
        |^tests/tt_metal/tt_metal/common/device_fixture\.hpp$
        |^tests/tt_metal/tt_metal/eth/test_erisc_app_direct_send\.cpp$
        |^tests/tt_metal/tt_metal/perf_microbenchmark/routing/kernels/traffic_gen_rx\.cpp$
        |^tests/tt_metal/tt_metal/perf_microbenchmark/routing/kernels/traffic_gen_tx\.cpp$
        |^tests/tt_metal/tt_metal/perf_microbenchmark/routing/test_bi_tunnel\.cpp$
        |^tests/tt_metal/tt_metal/perf_microbenchmark/routing/test_common\.hpp$
        |^tests/tt_metal/tt_metal/perf_microbenchmark/routing/test_mux_demux\.cpp$
        |^tests/tt_metal/tt_metal/perf_microbenchmark/routing/test_mux_demux_2level\.cpp$
        |^tests/tt_metal/tt_metal/perf_microbenchmark/routing/test_tunnel_1cq\.cpp$
        |^tests/tt_metal/tt_metal/perf_microbenchmark/routing/test_tunnel_2cq\.cpp$
        |^tests/tt_metal/tt_metal/perf_microbenchmark/routing/test_tx_rx\.cpp$
        |^tests/tt_metal/tt_metal/perf_microbenchmark/routing/test_uni_tunnel\.cpp$
        |^tests/tt_metal/tt_metal/perf_microbenchmark/routing/test_uni_tunnel_single_chip\.cpp$
        |^tests/tt_metal/tt_metal/perf_microbenchmark/routing/test_vc_mux_demux\.cpp$
        |^tests/tt_metal/tt_metal/perf_microbenchmark/routing/test_vc_uni_tunnel\.cpp$
        |^tests/tt_metal/tt_metal/test_compile_sets_kernel_binaries\.cpp$
        |^tests/ttnn/unit_tests/gtests/ccl/kernels/fabric_erisc_datamover_sender_worker_sender\.cpp$
        |^tests/ttnn/unit_tests/gtests/ccl/kernels/fabric_worker_sender_multi_input\.cpp$
        |^tests/ttnn/unit_tests/gtests/ccl/kernels/test_kernels\.common\.hpp$
        |^tests/ttnn/unit_tests/gtests/ccl/test_fabric_erisc_data_mover_loopback_with_workers\.cpp$
        |^tests/ttnn/unit_tests/gtests/test_graph_basic\.cpp$
        |^tt_metal/distributed/mesh_device\.cpp$
        |^tt_metal/hw/ckernels/blackhole/metal/llk_api/llk_unpack_tilize_api\.h$
        |^tt_metal/impl/buffers/buffer\.cpp$
        |^tt_metal/impl/buffers/buffer\.hpp$
        |^tt_metal/impl/device/device\.cpp$
        |^tt_metal/impl/device/device\.hpp$
        |^tt_metal/impl/dispatch/arch\.cpp$
        |^tt_metal/impl/dispatch/arch\.hpp$
        |^tt_metal/impl/dispatch/command_queue\.cpp$
        |^tt_metal/impl/dispatch/command_queue\.hpp$
        |^tt_metal/impl/dispatch/dispatch_core_manager\.hpp$
        |^tt_metal/impl/dispatch/dispatch_kernels\.cpp$
        |^tt_metal/impl/dispatch/dispatch_kernels\.hpp$
        |^tt_metal/impl/dispatch/kernels/eth_tunneler\.cpp$
        |^tt_metal/impl/dispatch/kernels/packet_demux\.cpp$
        |^tt_metal/impl/dispatch/kernels/packet_mux\.cpp$
        |^tt_metal/impl/dispatch/kernels/packet_queue\.hpp$
        |^tt_metal/impl/dispatch/kernels/packet_queue_ctrl\.hpp$
        |^tt_metal/impl/dispatch/kernels/vc_eth_tunneler\.cpp$
        |^tt_metal/impl/dispatch/kernels/vc_packet_router\.cpp$
        |^tt_metal/impl/kernels/kernel\.cpp$
        |^tt_metal/impl/kernels/kernel\.hpp$
        |^tt_metal/impl/program/program\.cpp$
        |^tt_metal/impl/program/program\.hpp$
        |^tt_metal/jit_build/genfiles\.cpp$
        |^tt_metal/jit_build/genfiles\.hpp$
        |^tt_metal/llrt/llrt\.cpp$
        |^tt_metal/llrt/llrt\.hpp$
        |^tt_metal/llrt/rtoptions\.cpp$
        |^tt_metal/llrt/rtoptions\.hpp$
        |^tt_metal/llrt/tt_cluster\.cpp$
        |^tt_metal/llrt/tt_cluster\.hpp$
        |^tt_metal/llrt/tt_memory\.h$
        |^tt_metal/tt_metal\.cpp$
        |^ttnn/cpp/pybind11/tensor\.cpp$
        |^ttnn/cpp/ttnn/device_operation\.hpp$
        |^ttnn/cpp/ttnn/graph/graph_processor\.cpp$
        |^ttnn/cpp/ttnn/graph/graph_processor\.hpp$
        |^ttnn/cpp/ttnn/operations/bernoulli/device/bernoulli_device_operation\.cpp$
        |^ttnn/cpp/ttnn/operations/bernoulli/device/bernoulli_device_operation\.hpp$
        |^ttnn/cpp/ttnn/operations/ccl/all_gather/all_gather\.cpp$
        |^ttnn/cpp/ttnn/operations/ccl/all_gather/device/all_gather_op\.hpp$
        |^ttnn/cpp/ttnn/operations/ccl/all_gather/device/kernels/dataflow/worker_ring_gather_utils\.hpp$
        |^ttnn/cpp/ttnn/operations/ccl/all_gather_v2/device/all_gather_op\.cpp$
        |^ttnn/cpp/ttnn/operations/ccl/all_gather_v2/device/all_gather_op\.hpp$
