---
- name: Set up package dependencies on node
  hosts: all
  become: true
  tasks:
    - name: Install packages
      apt:
        update_cache: yes
        pkg:
          - jq=1.6-1ubuntu0.20.04.1
