---
- name: Mount MLPerf now and on reboot
  hosts: all
  tasks:
    - name: Download weka install script
      become: yes
      ansible.builtin.uri:
        url: "http://172.27.36.114:14000/dist/v1/install"
        dest: /opt/tt_metal_infra/scripts/install_weka.sh
        status_code: [200, 304]
    - name: Make weka install script executable
      become: yes
      ansible.builtin.file:
        path: /opt/tt_metal_infra/scripts/install_weka.sh
        mode: ugo+x
    - name: Execute weka install script
      become: yes
      ansible.builtin.shell:
        cmd: /opt/tt_metal_infra/scripts/install_weka.sh
      async: 600
      poll: 5
    - name: Make MLPerf dir for mounting
      become: yes
      ansible.builtin.file:
        path: /mnt/MLPerf
        state: directory
    - name: Copy mnt-MLPerf.mount config
      become: yes
      ansible.builtin.copy:
        src: "../../scripts/mnt-MLPerf.mount-{{ machine_type }}"
        dest: /etc/systemd/system/mnt-MLPerf.mount
    - name: Enable mnt-MLPerf.mount
      become: yes
      ansible.builtin.systemd:
        name: mnt-MLPerf.mount
        enabled: true
        daemon_reload: true
      async: 450
      poll: 5
    - name: Start mnt-MLPerf.mount
      become: yes
      ansible.builtin.systemd:
        name: mnt-MLPerf.mount
        state: started
      async: 450
      poll: 5
