---
- name: Set up package dependencies on node
  hosts: all
  become: true
  tasks:
    - name: Install packages
      apt:
        update_cache: yes
        pkg:
          - software-properties-common=0.99.9.11
          - build-essential=12.8ubuntu1.1
          - python3.8-venv=3.8.10-0ubuntu1~20.04.7
          - libgoogle-glog-dev=0.4.0-1build1
          - ruby=1:2.7+1
          - libyaml-cpp-dev=0.6.2-4ubuntu1
          - git=1:2.25.1-1ubuntu3.11
          - git-lfs=2.9.2-1
          - clang-6.0=1:6.0.1-14
          - libboost-all-dev=1.71.0.0ubuntu2
          - libsndfile1=1.0.28-7ubuntu0.1

- name: Install doxygen
  hosts: all
  tasks:
    - name: Remove current installation of infra_testing
      file:
        path: doxygen-1.9.6
        state: absent
    - name: Remove existing oxygen download
      file:
        path: doxygen-1.9.6.linux.bin.tar.gz
        state: absent
    - name: Download doxygen
      ansible.builtin.uri:
        url: "https://www.doxygen.nl/files/doxygen-1.9.6.linux.bin.tar.gz"
        dest: "/home/{{ ansible_user }}/"
        status_code: [200, 304]
    - name: Unpack doxygen
      ansible.builtin.unarchive:
        src: doxygen-1.9.6.linux.bin.tar.gz
        dest: "/home/{{ ansible_user }}/"
        remote_src: yes
    - name: Install doxygen
      become: yes
      ansible.builtin.shell:
        chdir: "/home/{{ ansible_user }}/doxygen-1.9.6"
        cmd: "make install"

- name: Create infra_testing assets and verify devices
  hosts: all
  tasks:
    - name: Remove current installation of infra_testing
      file:
        path: infra_testing
        state: absent
    - name: Make workspace and syseng directories
      file:
        path: infra_testing
        state: directory
    - name: Copy scripts
      ansible.builtin.copy:
        src: ../scripts/
        dest: "infra_testing/scripts/"
    - name: Copy assets
      ansible.builtin.copy:
        src: ../assets/
        dest: "infra_testing/assets/"
    - name: Unpack driver tar directly
      ansible.builtin.unarchive:
        src: "/home/{{ ansible_user }}/infra_testing/assets/tt_driver/ttkmd_1.14.tar.gz"
        dest: "/home/{{ ansible_user }}/infra_testing/assets/tt_driver/"
        remote_src: yes

- name: Install SMI
  hosts: all
  tasks:
    - name: Make infra_testing workspace for tt-smi
      file:
        path: "infra_testing/tt_smi/{{ arch }}"
        state: directory
    - name: Copy SMI to workspace (assuming assets downloaded)
      ansible.builtin.copy:
        src: "../assets/tt_smi/{{ arch }}/tt-smi"
        dest: "infra_testing/tt_smi/{{ arch }}/tt-smi"
    - name: Install SMI to local bin
      become: yes
      ansible.builtin.copy:
        remote_src: true
        src: "infra_testing/tt_smi/{{ arch }}/tt-smi"
        dest: "/usr/local/bin/tt-smi"
    - name: Make tt-smi executable
      become: yes
      ansible.builtin.file:
        path: "/usr/local/bin/tt-smi"
        mode: ugo+x
    - name: Execute tt-smi as a test drive
      ansible.builtin.shell:
        cmd: "tt-smi --version"
