---
- name: Enable hugepages
  hosts: all
  tasks:
    - name: Get stat info of tt_metal_infra folder
      ansible.builtin.stat:
        path: "/opt/tt_metal_infra/scripts/"
      register: tt_metal_infra_stat
    - name: Assert syseng exists
      ansible.builtin.assert:
        that:
          - "tt_metal_infra_stat.stat.exists == true"
    - name: Get stat info of nr_hugepages
      ansible.builtin.stat:
        path: "/sys/kernel/mm/hugepages/hugepages-1048576kB/nr_hugepages"
      register: nr_hugepages_stat
    - name: Assert nr_hugepages exists
      ansible.builtin.assert:
        that:
          - "nr_hugepages_stat.stat.exists == true"
    - name: Get stat info of dev/tenstorrent
      ansible.builtin.stat:
        path: "/dev/tenstorrent"
      register: tt_dev_stat
    - name: Assert devices exist
      ansible.builtin.assert:
        that:
          - "tt_dev_stat.stat.exists == true"
    - name: Wait for settings to appear
      ansible.builtin.pause:
        minutes: 3
    - name: Execute script to enable
      become: yes
      shell:
        chdir: "/opt/tt_metal_infra/scripts/"
        cmd: "python3 setup_hugepages.py enable"
      environment:
        PATH: "{{ lookup('ansible.builtin.env', 'PATH', default=Undefined) }}"
      register: run_hugepages_enable_output
