---
- name: Enable hugepages
  hosts: all
  tasks:
    - name: Get stat info of infra_testing folder
      ansible.builtin.stat:
        path: "infra_testing/scripts/"
      register: infra_testing_stat
    - name: Assert syseng exists
      ansible.builtin.assert:
        that:
          - "infra_testing_stat.stat.exists == true"
    - name: Get stat info of nr_hugepages
      ansible.builtin.stat:
        path: "/sys/kernel/mm/hugepages/hugepages-1048576kB/nr_hugepages"
      register: nr_hugepages_stat
    - name: Assert nr_hugepages exists
      ansible.builtin.assert:
        that:
          - "nr_hugepages_stat.stat.exists == true"
    - name: Get stat info of dev/tenstorrent
      ansible.builtin.stat:
        path: "/dev/tenstorrent"
      register: tt_dev_stat
    - name: Assert devices exist
      ansible.builtin.assert:
        that:
          - "tt_dev_stat.stat.exists == true"
    - name: Execute hugepages check
      shell:
        chdir: "infra_testing/scripts/"
        cmd: "python3 setup_hugepages.py check"
