name: "[post-commit] all - Static checks, linters etc."

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - "main"
      - "fd-2/main"

jobs:
  check-spdx-licenses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5.0.0
        with:
          cache: 'pip'
          cache-dependency-path: infra/requirements-infra.txt
      - uses: actions/cache@v4.0.0
        id: cache-tox-env
        with:
          path: |
            .tox/post_commit_check_spdx_licenses
      - name: Check SPDX licenses
        run: |
          tox -e post_commit_check_spdx_licenses
  check-metal-kernel-count:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check kernel count in base metal is less than maximum
        run: if (( $(find tt_metal/kernels/ -type f | wc -l) > 7 )); then exit 1; fi
  check-black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@23.10.1
  check-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ASPELL
        run: sudo apt-get install -y aspell
      - name: Run checks on docs
        run: TT_METAL_HOME=$(pwd) docs/spellcheck.sh
