name: "All post-commit tests"

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      build-type:
        required: false
        default: Release
        type: choice
        options:
          - Release
          - Debug
          - RelWithDebInfo
          - CI
  push:
    branches: ["main"]

permissions:
  actions: read
  contents: write
  pull-requests: write
  pages: write
  id-token: write
  packages: write

jobs:
  diff:
    runs-on: ubuntu-latest
    outputs:
      test_everything: ${{ steps.check_everything.outputs.changed }}
      test_tt_metal: ${{ steps.check_tt_metal.outputs.changed }}
      test_ttnn: ${{ steps.check_ttnn.outputs.changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure the full history is fetched
          submodules: recursive
      - name: Fetch main branch
        run: git fetch origin main
      - name: Check for changes in critical files
        id: check_everything
        run: |
          # Check for top-level CMakeLists.txt changes
          if git diff --name-only origin/main...HEAD | grep -q '^CMakeLists.txt'; then
            echo "changed=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          # Check for changes in dependencies directory
          if git diff --name-only origin/main...HEAD | grep -q '^dependencies/'; then
            echo "changed=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          # Check for changes in .gitmodules (submodule configuration changes)
          if git diff --name-only origin/main...HEAD | grep -q '^.gitmodules'; then
            echo "changed=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "changed=false" >> $GITHUB_OUTPUT
      - name: Check for changes in tt_metal
        id: check_tt_metal
        run: |
          if git diff --name-only origin/main...HEAD | grep -q '^tt_metal/'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
      - name: Check for changes in ttnn
        id: check_ttnn
        run: |
          if git diff --name-only origin/main...HEAD | grep -q '^ttnn/'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

  debug-diff:
    needs: diff
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        env:  # Pass outputs as environment variables
          TEST_EVERYTHING: ${{ needs.diff.outputs.test_everything }}
          TEST_TT_METAL: ${{ needs.diff.outputs.test_tt_metal }}
          TEST_TTNN: ${{ needs.diff.outputs.test_ttnn }}
        run: |
          echo "test_everything: $TEST_EVERYTHING"
          echo "test_tt_metal: $TEST_TT_METAL"
          echo "test_ttnn: $TEST_TTNN"

  build-wheels:
    needs: build-artifact
    strategy:
      matrix:
        # Since pre-compiled builds only run on 20.04, we can only test on 20.04 for now
        # The full 22.04 flow can be tested without precompiled
        os: [ubuntu-20.04]
        arch: [grayskull, wormhole_b0]
    uses: ./.github/workflows/_build-wheels-impl.yaml
    with:
      os: ${{ matrix.os }}
      arch: ${{ matrix.arch }}
      from-precompiled: true
    secrets: inherit
  test-wheels:
    needs: build-wheels
    uses: ./.github/workflows/_test-wheels-impl.yaml
    with:
      from-precompiled: true
    secrets: inherit
  build-docker-image-2004:
    uses: ./.github/workflows/build-docker-artifact.yaml
    secrets: inherit
    with:
      os: ubuntu-20.04-amd64
  build-docker-image-2204:
    uses: ./.github/workflows/build-docker-artifact.yaml
    secrets: inherit
    with:
      os: ubuntu-22.04-amd64
  build-artifact:
    needs: build-docker-image-2004
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
    with:
      build-docker: false
      build-type: ${{ inputs.build-type || 'Release' }}
  build-artifact-profiler:
    needs: build-docker-image-2004
    uses: ./.github/workflows/build-artifact.yaml
    with:
      tracy: true
      build-docker: false
      build-type: ${{ inputs.build-type || 'Release' }}
    secrets: inherit
  # UMD Unit Tests
  umd-unit-tests:
    needs:
      - build-artifact
      - diff
    if: ${{ needs.diff.outputs.test_everything == 'true' }}
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        test-group: [
          { arch: grayskull, runner-label: E150 },
          { arch: wormhole_b0, runner-label: N150 },
          { arch: wormhole_b0, runner-label: N300 },
        ]
    uses: ./.github/workflows/umd-unit-tests.yaml
    with:
      arch: ${{ matrix.test-group.arch }}
      runner-label: ${{ matrix.test-group.runner-label }}
  # Slow Dispatch Unit Tests
  sd-unit-tests:
    needs:
      - build-artifact
      - diff
    if: ${{ needs.diff.outputs.test_everything == 'true' || needs.diff.outputs.test_tt_metal == 'true' }}
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        test-group: [
          { arch: grayskull, runner-label: E150 },
          { arch: wormhole_b0, runner-label: N150 },
          { arch: wormhole_b0, runner-label: N300 },
        ]
    uses: ./.github/workflows/build-and-unit-tests.yaml
    with:
      arch: ${{ matrix.test-group.arch }}
      runner-label: ${{ matrix.test-group.runner-label }}
  # Fast Dispatch Unit Tests
  fast-dispatch-unit-tests:
    needs:
      - build-wheels
      - diff
    if: ${{ needs.diff.outputs.test_everything == 'true' || needs.diff.outputs.test_tt_metal == 'true' }}
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        test-group: [
          { arch: grayskull, runner-label: E150 },
          { arch: wormhole_b0, runner-label: N150 },
          { arch: wormhole_b0, runner-label: N300 },
        ]
    uses: ./.github/workflows/fast-dispatch-build-and-unit-tests.yaml
    with:
      arch: ${{ matrix.test-group.arch }}
      runner-label: ${{ matrix.test-group.runner-label }}
  # TTNN FD Unit tests
  ttnn-unit-tests:
    needs:
      - build-wheels
      - diff
    if: ${{ needs.diff.outputs.test_everything == 'true' || needs.diff.outputs.test_tt_metal == 'true' || needs.diff.outputs.test_ttnn == 'true' }}
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        test-group: [
          { arch: grayskull, runner-label: E150 },
          { arch: wormhole_b0, runner-label: N150 },
          { arch: wormhole_b0, runner-label: N300 },
        ]
    uses: ./.github/workflows/ttnn-post-commit.yaml
    with:
      arch: ${{ matrix.test-group.arch }}
      runner-label: ${{ matrix.test-group.runner-label }}
  # FD Model Tests
  models-unit-tests:
    needs:
      - build-wheels
      - diff
    if: ${{ needs.diff.outputs.test_everything == 'true' || needs.diff.outputs.test_tt_metal == 'true' || needs.diff.outputs.test_ttnn == 'true' }}
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        test-group: [
          { arch: grayskull, runner-label: E150 },
          { arch: wormhole_b0, runner-label: N150 },
          { arch: wormhole_b0, runner-label: N300 },
        ]
    uses: ./.github/workflows/models-post-commit.yaml
    with:
      arch: ${{ matrix.test-group.arch }}
      runner-label: ${{ matrix.test-group.runner-label }}
  # FD C++ Unit Tests
  cpp-unit-tests:
    needs:
      - build-artifact
      - diff
    if: ${{ needs.diff.outputs.test_everything == 'true' || needs.diff.outputs.test_tt_metal == 'true' }}
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        test-group: [
          { arch: grayskull, runner-label: E150 },
          { arch: wormhole_b0, runner-label: N150 },
          { arch: wormhole_b0, runner-label: N300 },
        ]
    uses: ./.github/workflows/cpp-post-commit.yaml
    with:
      arch: ${{ matrix.test-group.arch }}
      runner-label: ${{ matrix.test-group.runner-label }}
  code-analysis:
    needs: build-docker-image-2204
    uses: ./.github/workflows/code-analysis.yaml
    secrets: inherit
    with:
      os: ubuntu-22.04-amd64
  tt-train-cpp-unit-tests:
    needs: build-artifact
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        test-group: [
          { arch: wormhole_b0, runner-label: N150 },
          { arch: wormhole_b0, runner-label: N300 },
        ]
    uses: ./.github/workflows/tt-train-post-commit.yaml
    with:
      arch: ${{ matrix.test-group.arch }}
      runner-label: ${{ matrix.test-group.runner-label }}
  profiler-regression:
    needs: build-artifact-profiler
    uses: ./.github/workflows/run-profiler-regression.yaml
    secrets: inherit
  build-docs:
    needs: build-artifact
    uses: ./.github/workflows/docs-latest-public.yaml
    secrets: inherit
  build:
    needs: [build-artifact, build-docker-image-2204]
    uses: ./.github/workflows/build.yaml
    secrets: inherit
  # We used to use this for post-commit, but we didn't have enough runners
  # to support the number of developers running this workflow
  # build-and-test-measure-perf:
  # build-and-test-measure-perf-device:
