name: "All post-commit tests"

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      build-type:
        required: false
        default: Release
        type: choice
        options:
          - Release
          - Debug
          - RelWithDebInfo
          - CI
  push:
    branches: ["main"]

permissions:
  actions: read
  contents: write
  pull-requests: write
  pages: write
  id-token: write
  packages: write

jobs:
  build-wheels:
    needs: build-artifact
    strategy:
      matrix:
        # Since pre-compiled builds only run on 20.04, we can only test on 20.04 for now
        # The full 22.04 flow can be tested without precompiled
        os: [ubuntu-20.04]
        arch: [wormhole_b0]
    uses: ./.github/workflows/_build-wheels-impl.yaml
    with:
      os: ${{ matrix.os }}
      arch: ${{ matrix.arch }}
      from-precompiled: true
    secrets: inherit
  build-docker-image-2004:
    uses: ./.github/workflows/build-docker-artifact.yaml
    secrets: inherit
    with:
      os: ubuntu-20.04-amd64
  build-artifact:
    needs: build-docker-image-2004
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
    with:
      build-docker: false
      build-type: ${{ inputs.build-type || 'Release' }}
  # Models Unit Tests
  models-unit-tests:
    needs: build-wheels
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        test-group: [
          { arch: wormhole_b0, runner-label: N300 },
        ]
    uses: ./.github/workflows/models-post-commit.yaml
    with:
      arch: ${{ matrix.test-group.arch }}
      runner-label: ${{ matrix.test-group.runner-label }}
