name: "[post-commit] all - Static checks, linters etc."

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - "main"
      - "rkim/6857-test-merge-queue"
  merge_group:
    types: [checks_requested]

jobs:
  check-black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@23.10.1
