name: "Git bisect dispatch"

on:
  workflow_dispatch:
    inputs:
      arch:
        required: true
        type: choice
        options:
          - grayskull
          - wormhole_b0
          - blackhole
      tracy:
        required: true
        type: boolean
        default: false
        description: "Build with tracy enabled"
      runner-label:
        required: true
        type: choice
        options:
          - E150
          - N150
          - N300
          - P150
          - config-t3000
          - config-tg
          - config-tgg
        description: "Runner Type Label"
      extra-label:
        required: true
        type: string
        default: "in-service"
        description: "Secondary tag to filter runners"
      good-commit:
        required: true
        type: string
      bad-commit:
        required: true
        type: string
      command:
        required: true
        type: string
      timeout:
        required: true
        type: string
        description: "Timeout (eg: 5m, 1h)"
      patch:
        required: false
        type: string
        description: "Commit-ish to cherry-pick for each step"

run-name: "Bisect on ${{ inputs.runner-label }}"
jobs:
  build-artifact:
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
    with:
      tracy: ${{ inputs.tracy }}
      build-wheel: true
  test-dispatch:
    needs: build-artifact
    timeout-minutes: 1440
    runs-on:
      - ${{ inputs.runner-label }}
      - ${{ inputs.extra-label }}
    container:
      image: ${{ needs.build-artifact.outputs.ci-build-docker-image || 'failed to resolve docker image' }}
      env:
        TT_METAL_HOME: /work
        PYTHONPATH: /work
        LD_LIBRARY_PATH: /work/build/lib
        LOGURU_LEVEL: INFO
        ARCH_NAME: ${{ inputs.arch }}
      volumes:
        - ${{ github.workspace }}/docker-job:/work # Subdir to workaround https://github.com/actions/runner/issues/691
        - /dev/hugepages-1G:/dev/hugepages-1G
        - /mnt/MLPerf:/mnt/MLPerf
      options: "--device /dev/tenstorrent"
    defaults:
      run:
        shell: bash
        working-directory: /work # https://github.com/actions/runner/issues/878
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          path: docker-job # Here be dragons; keep it scoped to our desired volume, yet must be under github.workspace and be sure to clean up at the end
          fetch-depth: 0
      - name: ⬇️ Download tarball
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-artifact.outputs.build-artifact-name }}
          path: /work
      - name: Extract files
        run: tar -xvf ttm_any.tar
      - name: ⬇️ Download Wheel
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-artifact.outputs.wheel-artifact-name }}
          path: /work
      - name: Install Wheel
        run: |
          WHEEL_FILENAME=$(ls -1 *.whl)
          pip3 install $WHEEL_FILENAME
      - name: Run Git Bisect
        shell: bash
        env:
          GIT_COMMITTER_NAME: "GitHub Actions"
          GIT_COMMITTER_EMAIL: "actions@github.com"
        run: |
          ./tests/scripts/tt_bisect.sh -t ${{ inputs.timeout }} -f "${{ inputs.command }}" -b ${{ inputs.bad-commit }} -g ${{ inputs.good-commit }} -p "${{ inputs.patch }}"
      - name: Cleanup
        if: always()
        run: |
          # We are forced to checkout the repo into a subdir of the host's workdir; this pollutes the host
          # with root-owned files.  Be sure to clean up after ourselves in case we're on a non-ephemeral runner.
          rm -rf /__w/tt-metal/tt-metal/docker-job
