name: "(Blackhole) Blackhole nightly tests"

on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: "0 */12 * * *"  # Every day at 0:00 and 12:00 UTC

jobs:
  build-artifact:
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
    with:
      build-wheel: true
      version: 22.04
  fd-nightly:
    needs: build-artifact
    uses: ./.github/workflows/blackhole-nightly-tests-impl.yaml
    secrets: inherit
    with:
      docker-image: ${{ needs.build-artifact.outputs.ci-build-docker-image }}
      build-artifact-name: ${{ needs.build-artifact.outputs.build-artifact-name }}
      wheel-artifact-name: ${{ needs.build-artifact.outputs.wheel-artifact-name }}
