name: "[internal] Blackhole Demo tests impl"

on:
  workflow_call:

jobs:
  single-card-demo-tests:
    strategy:
      fail-fast: false
      matrix:
        test-group: [
          {
            name: "BH_functionality",
            arch: blackhole,
            runs-on: ["cloud-virtual-machine", "BH", "in-service"],
            cmd:
          },
          {
            name: "BH_performance",
            arch: blackhole,
            runs-on: ["BH", "bare-metal", "in-service"],
            cmd:
          }
        ]
    name: ${{ matrix.test-group.name }}
    env:
      ARCH_NAME: ${{ matrix.test-group.arch }}
      LOGURU_LEVEL: INFO
      LD_LIBRARY_PATH: ${{ github.workspace }}/build/lib
    runs-on: ${{ matrix.test-group.runs-on }}
    steps:
      - uses: tenstorrent/tt-metal/.github/actions/checkout-with-submodule-lfs@main
      - name: Enable Performance mode
        if: ${{ matrix.test-group.name == 'BH_performance' }}
        run: |
          sudo cpupower frequency-set -g performance
      - name: Set up dynamic env vars for build
        run: |
          echo "TT_METAL_HOME=$(pwd)" >> $GITHUB_ENV
      - uses: ./.github/actions/prepare-metal-run
      - uses: ./.github/actions/install-python-deps
      - name: Run demo regression tests
        timeout-minutes: 70
        run: |
          source ${{ github.workspace }}/python_env/bin/activate
          cd $TT_METAL_HOME
          export PYTHONPATH=$TT_METAL_HOME
          source ${{ github.workspace }}/tests/scripts/single_card/run_single_card_demo_tests.sh
          ${{ matrix.test-group.cmd }}
      - uses: tenstorrent/tt-metal/.github/actions/upload-artifact-with-job-uuid@main
        timeout-minutes: 10
        if: ${{ !cancelled() }}
        with:
          path: |
            generated/test_reports/
          prefix: "test_reports_"
      - name: Disable Performance mode
        if: ${{ matrix.test-group.name == 'BH_performance' }}
        run: |
          sudo cpupower frequency-set -g ondemand
