name: "Build UMD artifact"

on:
  workflow_call:
    inputs:
      arch:
        required: false
        type: string
        default: '["grayskull", "wormhole_b0", "blackhole"]'
      os:
        required: false
        type: string
        default: "ubuntu-20.04-amd64"
      build-docker:
        required: false
        type: boolean
        default: true
        description: "Build docker image"


jobs:
  build-docker-image:
    if: ${{ inputs.build-docker == true }}
    uses: ./.github/workflows/build-docker-artifact.yaml
    secrets: inherit
    with:
      os: ${{ inputs.os }}
  build-umd-artifact:
    needs: build-docker-image
    if: always()
    timeout-minutes: 5
    strategy:
      matrix:
        arch: ${{ fromJson(inputs.arch) }}
    env:
      ARCH_NAME: ${{ matrix.arch }}
    runs-on:
      - build
      - in-service
    steps:
      - uses: tenstorrent-metal/metal-workflows/.github/actions/checkout-with-submodule-lfs@v2.0.0
      - name: Build UMD device and tests
        run: |
      - name: Set up dynamic env vars for build
        run: |
          echo "RUNNER_UID=$(id -u)" >> $GITHUB_ENV
          echo "RUNNER_GID=$(id -g)" >> $GITHUB_ENV
      - name: Update submodules
        run: |
          git submodule update --init --recursive
      - name: Generate docker tag
        id: generate-docker-tag
        uses: ./.github/actions/generate-docker-tag
        with:
          image: ${{ inputs.os }}
      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull docker image
        run: docker pull ${{ env.TT_METAL_DOCKER_IMAGE_TAG }}
      - name: Build UMD tests and libs
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ env.TT_METAL_DOCKER_IMAGE_TAG }}
          # Hate the copy pasta - oh well, at least we keep it on e place
          options: |
            --rm
            --tmpfs /tmp
            -u ${{ env.RUNNER_UID }}:${{ env.RUNNER_GID }}
            --group-add 1457
            -v ${{ github.workspace }}:${{ github.workspace }}
            -v /etc/passwd:/etc/passwd:ro
            -v /etc/shadow:/etc/shadow:ro
            -v /etc/bashrc:/etc/bashrc:ro
            -v /home/ubuntu/.ccache-ci:/home/ubuntu/.ccache
            -v /mnt/MLPerf/ccache:/mnt/MLPerf/ccache
            -e ARCH_NAME=${{ matrix.arch }}
            -w ${{ github.workspace }}
          run: |
            nice -n 19 ./scripts/build_scripts/create_standalone_umd_lib.sh
      - name: Upload UMD Artifact
        uses: actions/upload-artifact@v4
        with:
          name: umd_${{ matrix.arch }}
          path: _umd/
          if-no-files-found: error
          # We may build multiple times for different cards - that's ok
          overwrite: true
