name: Post-commit main build and unit tests

on:
  workflow_dispatch:
  push:
    branches: ["main", "rkim/290-wheel"]

jobs:
  check-syseng-assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.CHECKOUT_TOKEN }}
      - name: Check asset download script
        env:
          GITHUB_TOKEN: ${{ secrets.CHECKOUT_TOKEN }}
        run: |
          cd infra/machine_setup
          ./scripts/download_public_machine_setup_assets.sh
