name: Post-commit main build and unit tests

on:
  push:
    branches: ["main"]

jobs:
  build-and-unit-tests:
    env:
      TT_METAL_HOME: ${{ vars.TT_METAL_HOME }}
      TT_METAL_ENV: ${{ vars.TT_METAL_ENV }}
    environment: dev
    runs-on:
      group: gs-pool
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.CHECKOUT_TOKEN }}
      - name: Build tt-metal and libs
        run: make build
      - name: Run pre/post regression tests
        run: ./tests/scripts/run_pre_post_commit_regressions.sh
