name: Build and deploy docs to Toronto VPN

on:
  push:
    branches: ["main"]

concurrency:
  group: '${{ github.workflow }}'
  cancel-in-progress: true

concurrency:
  group: '${{ github.workflow }}'
  cancel-in-progress: true

jobs:
  build-and-deploy-docs-toronto:
    uses: ./.github/workflows/docs-build-deploy.yaml
    with:
      runs-on-group: corporate-docs
    secrets:
      CHECKOUT_TOKEN: ${{ secrets.CHECKOUT_TOKEN }}
