name: "[post-commit] Python wheel build and test"

on:
  workflow_dispatch:
    inputs:
      from-precompiled:
        description: "Use precompiled assets for wheel build"
        default: True
        type: boolean
  workflow_call:

jobs:
  # To ensure we don't conflict with caller workflow build-artifacts
  build-artifact-for-precompiled:
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.from-precompiled }}
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
  build-wheels:
    needs: build-artifact-for-precompiled
    # Since this depends on build-artifact if we use from-precompiled, otherwise it's
    # a standalone job if we do not use from-precompiled
    if: always()
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        arch: [grayskull, wormhole_b0]
    uses: ./.github/workflows/eager-package.yaml
    with:
      os: ${{ matrix.os }}
      arch: ${{ matrix.arch }}
      from-precompiled: ${{ github.event_name == 'workflow_dispatch' && inputs.from-precompiled }}
  test-wheels-host:
    needs: build-wheels
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        runner-hw-info: [
          {arch: grayskull, type: E150},
          {arch: wormhole_b0, type: N150}
        ]
    runs-on: ["cloud-virtual-machine", "${{ matrix.runner-hw-info.type }}", "in-service"]
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: eager-dist-${{ matrix.os }}-${{ matrix.runner-hw-info.arch }}
      - name: Set up end-to-end tests environment
        run: ./tests/scripts/set_up_end_to_end_tests_env.sh
      - name: Activate env and run release tests - host
        shell: bash
        run: |
          source tests/end_to_end_tests/env/bin/activate
          cd tests/end_to_end_tests
          pytest -c conftest.py . -m eager_host_side
  test-wheels-silicon:
    needs: build-wheels
    strategy:
      matrix:
        os: [ubuntu-20.04]
        runner-hw-info: [
          {arch: grayskull, type: E150},
          {arch: wormhole_b0, type: N150},
          {arch: wormhole_b0, type: N300}
        ]
    runs-on: ["cloud-virtual-machine", "${{ matrix.runner-hw-info.type }}", "in-service"]
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: eager-dist-${{ matrix.os }}-${{ matrix.runner-hw-info.arch }}
      - name: Set up end-to-end tests environment
        run: ./tests/scripts/set_up_end_to_end_tests_env.sh
      - name: Activate env and run release tests - silicon
        timeout-minutes: 2
        shell: bash
        run: |
          source tests/end_to_end_tests/env/bin/activate
          cd tests/end_to_end_tests
          pytest -c conftest.py . -m eager_package_silicon
