name: eager - Package

on:
  workflow_call:
    inputs:
      environment:
        required: True
        type: string
    secrets:
      CHECKOUT_TOKEN:
        required: True

jobs:
  build-eager-package:
    strategy:
      matrix:
        arch: [grayskull, wormhole_b0]
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    environment: ${{ inputs.environment }}
    env:
      TT_METAL_ENV: ${{ vars.TT_METAL_ENV }}
      ARCH_NAME: ${{ matrix.arch }}
    steps:
      - uses: "./.github/actions/install-metal-deps-${{ matrix.os }}"
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.CHECKOUT_TOKEN }}
          lfs: true
      - name: Set up dyanmic env vars for build
        run: |
          echo "TT_METAL_HOME=$(pwd)" >> $GITHUB_ENV
      - name: Build tt-metal and libs
        run: make build
      # TODO: (RK) - should replace with single command python -m build
      - name: Build sdist
        run: |
          source build/python_env/bin/activate
          python -m build --sdist
      - name: Build wheel
        run: |
          source build/python_env/bin/activate
          python -m build --wheel
