name: eager - Package

on:
  workflow_call:
    inputs:
      environment:
        required: True
        type: string
    secrets:
      CHECKOUT_TOKEN:
        required: True

jobs:
  build-eager-package:
    strategy:
      matrix:
        arch: [grayskull, wormhole_b0]
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    environment: ${{ inputs.environment }}
    env:
      TT_METAL_ENV: ${{ vars.TT_METAL_ENV }}
      ARCH_NAME: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.CHECKOUT_TOKEN }}
          lfs: true
      - uses: ./.github/actions/install-metal-deps
        with:
          os: ${{ matrix.os }}
      - name: Set up dyanmic env vars for build
        run: |
          echo "TT_METAL_HOME=$(pwd)" >> $GITHUB_ENV
      - name: Create dev environment for packaging
        run: make python_env/dev
      - name: Build Python package distribution
        run: |
          source build/python_env/bin/activate
          python -m build
      - name: Upload distribution as artifact
        uses: actions/upload-artifact@v3
        with:
          name: eager-dist
          path: dist/
