name: "[post-commit] Fabric unit tests"

on:
  workflow_dispatch:

jobs:
  build-docker-artifact:
    uses: ./.github/workflows/build-docker-artifact.yaml
    secrets: inherit
  build-artifact:
    needs: build-docker-artifact
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
  # Fabric Unit Tests
  fabric-unit-tests:
    needs: build-artifact
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        test-group: [
          { arch: wormhole_b0, runner-label: N300 },
        ]
    uses: ./.github/workflows/fabric-build-and-unit-tests.yaml
    with:
      arch: ${{ matrix.test-group.arch}}
      runner-label: ${{ matrix.test-group.runner-label}}
