name: Nightly fast dispatch tests

on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  build-artifact:
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
  fd-nightly:
    needs: build-artifact
    strategy:
      # Do not fail-fast because we need to ensure all tests go to completion
      # so we try not to get hanging machines
      fail-fast: false
      matrix:
        test-group:
          [
            { name: "Common models GS", arch: grayskull, cmd: ARCH_NAME=grayskull tests/scripts/nightly/run_common_models.sh },
            { name: "Common models N300 WH B0", arch: wormhole_b0, cmd: ARCH_NAME=wormhole_b0 tests/scripts/nightly/run_common_models.sh },
            { name: "GS-only ttnn nightly", arch: grayskull, cmd: tox -e nightly_fast_dispatch_ttnn },
            { name: "GS-only models", arch: grayskull, cmd: ARCH_NAME=grayskull tox -e nightly_fast_dispatch_gs_only },
            { name: "N300 WH-only models", arch: wormhole_b0, cmd: ARCH_NAME=wormhole_b0 tox -e nightly_fast_dispatch_wh_only },
            { name: "API tests GS", arch: grayskull, cmd: ARCH_NAME=grayskull MODEL_TYPE=api tox -e nightly_fast_dispatch },
            { name: "API tests N300 WH B0", arch: wormhole_b0, cmd: ARCH_NAME=wormhole_b0 MODEL_TYPE=api tox -e nightly_fast_dispatch },
          ]
    name: FD ${{ matrix.test-group.name }} ${{ matrix.test-group.arch }}
    env:
      TT_METAL_ENV: ${{ vars.TT_METAL_ENV }}
      ARCH_NAME: ${{ matrix.test-group.arch }}
      CONFIG: ci
      LOGURU_LEVEL: INFO
    runs-on: model-runner-${{ matrix.test-group.arch }}
    steps:
      - uses: tenstorrent-metal/metal-workflows/.github/actions/checkout-with-submodule-lfs@v2.0.0
      - name: Ensure weka mount is active
        run: |
          sudo systemctl restart mnt-MLPerf.mount
          sudo /etc/rc.local
          ls -al /mnt/MLPerf/bit_error_tests
      - name: Set up dyanmic env vars for build
        run: |
          echo "TT_METAL_HOME=$(pwd)" >> $GITHUB_ENV
      - uses: actions/download-artifact@v4
        with:
          name: TTMetal_build_${{ matrix.test-group.arch }}
      - name: Extract files
        run: tar -xvf ttm_${{ matrix.test-group.arch }}.tar
      - uses: ./.github/actions/install-python-deps
      - name: Run frequent reg tests scripts
        timeout-minutes: 40
        run: |
          source ${{ github.workspace }}/python_env/bin/activate
          cd $TT_METAL_HOME
          export PYTHONPATH=$TT_METAL_HOME
          VENV_DIR=${{ github.workspace }}/python_env ARCH_NAME=${{ matrix.arch }} FREQUENT_TYPE=${{ matrix.frequent-type }} tox -e nightly_fast_dispatch
