name: "(Single-card) Tests for new models"

on:
  workflow_dispatch:
    inputs:
      build-type:
        required: false
        default: Release
        type: choice
        options:
          - Release
          - Debug
          - RelWithDebInfo
          - CI
  push:
    branches:
      - rkim/15020-full-pipe

permissions:
  actions: read
  contents: write
  pull-requests: write
  pages: write
  id-token: write
  packages: write

jobs:
  all-post-commit-tests:
    uses: ./.github/workflows/all-post-commit-workflows.yaml
    secrets: inherit
  device-perf-single-card:
    uses: ./.github/workflows/perf-device-models-impl.yaml
    secrets: inherit
  e2e-model-perf-single-card:
    uses: ./.github/workflows/perf-models-impl.yaml
    secrets: inherit
  nightly-single-card:
    uses: ./.github/workflows/fast-dispatch-full-regressions-and-models-impl.yaml
    secrets: inherit
  demos-single-card:
    uses: ./.github/workflows/single-card-demo-tests-impl.yaml
    secrets: inherit
