name: Scheduled build and run all regressions and models

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *"

jobs:
  build-and-test-all:
    environment: dev
    runs-on:
      group: gs-pool
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.CHECKOUT_TOKEN }}
      - name: Build tt-metal
        run: make build
      - name: Build tt-metal tests
        run: make tests
      - name: Run all reg scripts
        run: |
          ./tests/scripts/run_reg_scripts.sh
