name: Scheduled build and run all regressions and models

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  build-and-test-all:
    environment: dev
    runs-on:
      group: gs-pool
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.CHECKOUT_TOKEN }}
      - name: Run clean + build + all reg tests scripts
        run: ./tests/scripts/run_reg_scripts.sh
        env:
          TT_METAL_HOME: ${{ vars.TT_METAL_HOME }}
          TT_METAL_ENV: ${{ vars.TT_METAL_ENV }}
