name: Scheduled slow dispatch frequent build and run

on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: "0 1,6 * * *"

jobs:
  build-and-test-frequent:
    strategy:
      # Do not fail-fast because we need to ensure all tests go to completion
      # so we try not to get hanging machines
      fail-fast: false
      matrix:
        runner-info: [
          {arch: grayskull, runs-on: ["model-runner-grayskull"]},
          # N150
          {arch: wormhole_b0, runs-on: ["model-runner-wormhole_b0", "issue-hugepages-upgrade"]},
        ]
    env:
      TT_METAL_ENV: ${{ vars.TT_METAL_ENV }}
      ARCH_NAME: ${{ matrix.runner-info.arch }}
      TT_METAL_SLOW_DISPATCH_MODE: 1
    environment: dev
    runs-on: ${{ matrix.runner-info.runs-on }}
    steps:
      - uses: tenstorrent-metal/metal-workflows/.github/actions/checkout-with-submodule-lfs@main
        with:
          token: ${{ secrets.CHECKOUT_TOKEN }}
      - name: Set up dyanmic env vars for build
        run: |
          echo "TT_METAL_HOME=$(pwd)" >> $GITHUB_ENV
      - name: Build tt-metal and libs
        run: make build
      - name: Run frequent reg tests scripts
        timeout-minutes: 300
        run: ./tests/scripts/run_tests.sh --tt-arch ${{ matrix.runner-info.arch }} --pipeline-type frequent --dispatch-mode slow
