name: Scheduled build and run all regressions and models

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *"

jobs:
  build-and-test-all:
    environment: dev
    runs-on:
      group: gs-pool
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.CHECKOUT_TOKEN }}
      - name: Run clean + build + all reg tests scripts
        run: |
          env ./tests/scripts/run_reg_scripts.sh
