name: Compute Public API Surface

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: ["main"]

jobs:
  compute_and_notify:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Ensures latest stable Python 3

      - name: Install dependencies
        run: python3 -m pip install tree-sitter tree-sitter-cpp

      - name: Download script
        run: |
          wget -O compute_public_api_surface.py https://gist.githubusercontent.com/ayerofieiev-tt/ea5fe814bd6741b08708883669ed022d/raw/9e8b193cf26071877a6d663fb89b0223e709406f/compute_public_api_surface.py

      - name: Run script
        id: compute_api
        run: |
          output=$(python3 compute_public_api_surface.py)
          echo "result=$output" >> $GITHUB_ENV

      - name: Parse JSON output
        id: parse_json
        run: |
          echo '${{ env.result }}' | jq -r '"date=\(.date)\nnum_files=\(.num_files)\nnum_types=\(.num_types)\nnum_methods=\(.num_methods)"' >> $GITHUB_ENV

      - name: Send Slack message to a channel
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": "*Public API Surface Report* 📊\n
              📅 *Date:* ${{ env.date }}\n
              📂 *Files:* ${{ env.num_files }}\n
              🔠 *Types:* ${{ env.num_types }}\n
              🔧 *Methods:* ${{ env.num_methods }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL_ID: C08BAGE4410
