name: "[post-commit] models - Run models on bare metal only for functionality check"

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 4 * * *"

jobs:
  build-and-run-bm-models:
    strategy:
      # Do not fail-fast because we need to ensure all tests go to completion
      # so we try not to get hanging machines
      fail-fast: false
      matrix:
        arch: [grayskull]
    env:
      TT_METAL_ENV: ${{ vars.TT_METAL_ENV }}
      ARCH_NAME: ${{ matrix.arch }}
    environment: dev
    runs-on: ["${{ matrix.arch }}", "self-reset"]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.CHECKOUT_TOKEN }}
          lfs: true
      - name: Set up dynamic env vars for build
        run: |
          echo "TT_METAL_HOME=$(pwd)" >> $GITHUB_ENV
          echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV
      - name: Build tt-metal and libs
        run: make build
      - name: Run metal bert
        timeout-minutes: 10
        run: |
          source build/python_env/bin/activate
          ./tests/scripts/run_tests.sh --tt-arch ${{ matrix.arch }} --pipeline-type metal_bert_bm
      - name: Check metal-bert-15 perf report exists
        id: check-perf-report
        run: |
          ls -hal
          export PERF_REPORT_FILENAME=perf_bert15_$(date +%Y_%m_%d).csv
          ls -hal $PERF_REPORT_FILENAME
          echo "perf_report_filename=$PERF_REPORT_FILENAME" >> "$GITHUB_OUTPUT"
      - name: Upload perf report
        uses: actions/upload-artifact@v3
        with:
          name: metal-bert-15-perf-report-csv
          path: "${{ steps.check-perf-report.outputs.perf_report_filename }}"
