name: Package and release

on:
  push:
    branches: ["release"]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  create-changelog:
    permissions: read-all
    runs-on: ubuntu-latest
    steps:
      - name: Create changelog
        id: create-changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ignorePreReleases: true
          failOnError: true
          outputFile: CHANGELOG.txt
      - name: Output changelog
        run: cat CHANGELOG.txt
      - name: Upload changelog as artifact
        uses: actions/upload-artifact@v3
        with:
          name: changelog
          path: CHANGELOG.txt
  build-eager-package:
    strategy:
      matrix:
        os: [ubuntu-20.04]
        arch: [grayskull, wormhole_b0]
    uses: ./.github/workflows/eager-package.yaml
    with:
      environment: dev
      os: ${{ matrix.os }}
      arch: ${{ matrix.arch }}
    secrets:
      CHECKOUT_TOKEN: ${{ secrets.CHECKOUT_TOKEN }}
  create-and-upload-draft-release:
    needs: [
      create-changelog,
      build-eager-package,
    ]
    strategy:
      matrix:
        os: [ubuntu-20.04]
        arch: [grayskull, wormhole_b0]
    # May accidentally create two releases without restricting to 1 job
    concurrency: create_upload_draft_release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download eager Python packages
        uses: actions/download-artifact@v3
        with:
          name: eager-dist-${{ matrix.os }}-${{ matrix.arch }}
      - name: Create VERSION
        run: echo v0.37.0 > VERSION
      - name : Download changelog
        uses: actions/download-artifact@v3
        with:
          name: changelog
      - name: Assert wheels exist
        # Issue #3443 wants us to delete the wheel from the release assets.
        # We are still committed to making this eventually work for proper
        # releases to allow for easier installing for Python users.
        run: ls -arhl metal_libs-*+*.whl
      - name: Download syseng assets for release
        env:
          GITHUB_TOKEN: ${{ secrets.CHECKOUT_TOKEN }}
        run: |
          cd infra/machine_setup
          ./scripts/download_public_machine_setup_assets.sh -r
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v0.37.0
          name: syseng-assets-release-test
          draft: true
          body_path: CHANGELOG.txt
          files: |
            VERSION
            CHANGELOG.txt
            infra/machine_setup/assets/*
          fail_on_unmatched_files: true
