name: "(Single-card) Model perf tests"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2,7,10,14,17,20,23 * * *"
  workflow_call:

jobs:
  build-artifact:
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
  build-artifact-profiler:
    uses: ./.github/workflows/build-artifact.yaml
    with:
      arch: '["wormhole_b0"]'
      tracy: true
    secrets: inherit
  models-perf:
    needs: [build-artifact, build-artifact-profiler]
    uses: ./.github/workflows/perf-models-impl.yaml
    secrets: inherit
