name: PR Comment Trigger Workflow

on:
  pull_request:
    types: [opened, edited, reopened]
  issue_comment:
    types: [created]

jobs:
  detect_trigger:
    runs-on: ubuntu-latest
    outputs:
      mirror_triggered: ${{ steps.mirror_check.outputs.triggered }}
      test_triggered: ${{ steps.test_check.outputs.triggered }}
    steps:
      - name: Check for trigger (mirror)
        uses: khan/pull-request-comment-trigger@v1.1.0
        id: mirror_check
        with:
          trigger: ':mirror:'
          reaction: eyes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for trigger (test)
        uses: khan/pull-request-comment-trigger@v1.1.0
        id: test_check
        with:
          trigger: ':test:'
          reaction: rocket
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  mirror_fetch_pr_info:
    if: needs.detect_trigger.outputs.mirror_triggered == 'true'
    runs-on: ubuntu-latest    
    outputs:
      source: ${{ steps.set_source.outputs.source }}
    steps:
      - name: Find pull request
        id: find_pr
        uses: peter-evans/find-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
      - name: Set source
        id: set_source
        run: |
          echo "source=${{ steps.find_pr.outputs.head_repo_owner }}:${{ steps.find_pr.outputs.head_ref }}" >> $GITHUB_OUTPUT

  mirror:
    needs: mirror_fetch_pr_info
    if: needs.detect_trigger.outputs.mirror_triggered == 'true'
    uses: ./.github/workflows/mirror-fork-branch.yaml
    with:
      source: "${{ needs.mirror_fetch_pr_info.outputs.source }}"

  test:
    if: needs.detect_trigger.outputs.test_triggered == 'true'
    uses: ./.github/workflows/all-post-commit-workflows.yaml
    with:
      build-type: Release

  post_comment:
    needs: [mirror, test]
    if: needs.detect_trigger.outputs.mirror_triggered == 'true' || needs.detect_trigger.outputs.test_triggered == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Post workflow run link comment on PR
        uses: mshick/add-pr-comment@v2
        with:
          issue: ${{ github.event.issue.number || github.event.pull_request.number }}
          message: |
            ✨ Workflow run is available [here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
