name: Pull Request Stats

on:
  pull_request:
    types: [opened]

jobs:
  stats:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@master
        with:
          token: ${{ secrets.ADD_A_PERSONAL_ACCESS_TOKEN }}
          period: 187
          limit: 0
