name: "Create and Publish Release Docker Image"

on:
  workflow_dispatch:
jobs:
  build-artifact:
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
  publish-release-image:
    needs: build-artifact
    uses: ./.github/workflows/publish-release-image.yaml
    secrets: inherit
    with:
      version: dev-${GITHUB_REF_NAME//\//-}
      is_major_version: false
