name: "Create and Publish Release Docker Image"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  static-checks:
    uses: ./.github/workflows/all-static-checks.yaml
    secrets: inherit
  build-artifact:
    needs: static-checks
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
  publish-release-image:
    needs: build-artifact
    uses: ./.github/workflows/publish-release-image.yaml
    secrets: inherit
    with:
      version: test
      is_major_version: false
