on:
  schedule:
    - cron: "0 0 * * *" # Runs every night at midnight

jobs:
  remove-stale-branches:
    runs-on: ubuntu-latest
    steps:
      - uses: fpicalausa/remove-stale-branches@v2.0.1
        with:
          dry-run: true
          days-before-branch-stale: 365 # Branches stale for 1 year
