name: "[internal] Remove Stale Branches"

on:
  schedule:
    - cron: "0 */6 * * *"   # Runs at midnight, 6AM, noon, 6pm
  workflow_dispatch: # Allows manual trigger

jobs:
  remove-stale-branches:
    runs-on: ubuntu-latest
    steps:
      - uses: blozano-tt/remove-stale-branches@5286c692f7f58cc0b4fc5b096c834e013616587b
        with:
          dry-run: false
          days-before-branch-stale: 180 # Branches stale for ~6 months
          ignore-unknown-authors: true
          default-recipient: "blozano-tt"
          operations-per-run: 30
