name: "[post-commit] metal - Run profiler regression"

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  workflow_call:

jobs:
  run-profiler-regression:
    strategy:
      # Do not fail-fast because we need to ensure all tests go to completion
      # so we try not to get hanging machines
      fail-fast: false
      matrix:
        runner-info: [
          {arch: grayskull, runs-on: ["grayskull", "fw-date-2023-06-28"]},
          # N150
          {arch: wormhole_b0, runs-on: ["wormhole_b0", "fw-date-2023-08-08", "multi-chip-num-pcie-1", "multi-chip-num-chips-1"]},
          # N300
          {arch: wormhole_b0, runs-on: ["wormhole_b0", "fw-date-2023-08-08", "multi-chip-num-pcie-1", "multi-chip-num-chips-2"]},
        ]
    env:
      TT_METAL_ENV: ${{ vars.TT_METAL_ENV }}
      ARCH_NAME: ${{ matrix.runner-info.arch }}
    environment: dev
    runs-on: ${{ matrix.runner-info.runs-on }}
    steps:
      - uses: tenstorrent-metal/metal-workflows/.github/actions/checkout-with-submodule-lfs@main
        with:
          token: ${{ secrets.CHECKOUT_TOKEN }}
      - name: Set up dynamic env vars for build
        run: |
          echo "TT_METAL_HOME=$(pwd)" >> $GITHUB_ENV
      - name: Build tt-metal and libs
        run: |
          ./scripts/build_scripts/build_with_profiler_opt.sh
      - name: Run profiler regression tests
        run: |
          ./tests/scripts/run_profiler_regressions.sh
