name: "(Single-card) Demo tests"

on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: "0 */6 * * 1,2,3,4,5"
    - cron: "0 */4 * * 0,6"

jobs:
  build-artifact:
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
  single-card-demo-tests:
    needs: build-artifact
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        test-group: [
          { arch: wormhole_b0, runner-label: N150 },
          { arch: wormhole_b0, runner-label: N300 },
        ]
    uses: ./.github/workflows/single-card-demo-tests-impl.yaml
    with:
      arch: ${{ matrix.test-group.arch}}
      runner-label: ${{ matrix.test-group.runner-label}}
