name: "[stress] Virtual machine across WH+GS, for FD and SD"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

jobs:
  stress-gs-fd:
    uses: ./.github/workflows/stress-vm-gs-fd.yaml
    secrets: inherit
  stress-gs-sd:
    uses: ./.github/workflows/stress-vm-gs-sd.yaml
    secrets: inherit
  stress-wh-fd:
    uses: ./.github/workflows/stress-vm-wh-fd.yaml
    secrets: inherit
  stress-wh-sd:
    uses: ./.github/workflows/stress-vm-wh-sd.yaml
    secrets: inherit
