name: "[stress] Bare metal across WH+GS, for FD"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

jobs:
  stress-gs-fd:
    uses: ./.github/workflows/stress-bm-gs-fd.yaml
    secrets: inherit
  stress-wh-fd:
    uses: ./.github/workflows/stress-bm-wh-fd.yaml
    secrets: inherit
