name: "[stress] Slow Dispatch post-commit on GS VM"

on:
  workflow_call:

jobs:
  stress-build-and-unit-tests:
    timeout-minutes: 1440
    strategy:
      # Do not fail-fast because we need to ensure all tests go to completion
      # so we try not to get hanging machines
      fail-fast: false
      matrix:
        runner-info: [
          {arch: grayskull, runs-on: ["grayskull", "cloud-virtual-machine"], machine-type: "virtual_machine"},
        ]
    env:
      TT_METAL_ENV: ${{ vars.TT_METAL_ENV }}
      ARCH_NAME: ${{ matrix.runner-info.arch }}
      TT_METAL_SLOW_DISPATCH_MODE: 1
      TT_METAL_WATCHER: 60
    environment: dev
    runs-on: ${{ matrix.runner-info.runs-on }}
    steps:
      - uses: ./.github/actions/stress-build-and-run
        with:
          arch: ${{ matrix.runner-info.arch }}
          dispatch: 'slow'
          machine: ${{ matrix.runner-info.machine-type }}
          token: ${{ secrets.CHECKOUT_TOKEN }}
