# Build and run tests that frequently hang cards
name: "test-frequently-hangs"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  build-and-unit-tests:
    strategy:
      # Do not fail-fast because we need to ensure all tests go to completion
      # so we try not to get hanging machines
      fail-fast: false
      matrix:
        arch: [grayskull, wormhole_b0]
    env:
      TT_METAL_ENV: ${{ vars.TT_METAL_ENV }}
      ARCH_NAME: ${{ matrix.arch }}
    environment: dev
    runs-on: ["${{ matrix.arch }}", "self-reset"]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.CHECKOUT_TOKEN }}
          lfs: true
      - name: Set up dynamic env vars for build
        run: |
          echo "TT_METAL_HOME=$(pwd)" >> $GITHUB_ENV
      - name: Run tests
        run: |
          ./tests/scripts/run_tests.sh --tt-arch $ARCH_NAME --pipeline-type frequently_hangs
