name: "Custom test dispatch"

on:
  workflow_dispatch:
    inputs:
      arch:
        required: true
        type: choice
        options:
          - grayskull
          - wormhole_b0
      runner-label:
        required: true
        type: string
      command:
        required: true
        type: string
      description:
        type: string
        required: false

jobs:
  build-artifact:
    uses: ./.github/workflows/build-artifact.yaml
    with:
      arch: ${{ inputs.arch }}
    secrets: inherit
  test-dispatch:
    needs: build-artifact
    timeout-minutes: 1440
    env:
      TT_METAL_ENV: ${{ vars.TT_METAL_ENV }}
      ARCH_NAME: ${{ inputs.arch }}
    environment: dev
    runs-on: ${{ inputs.runner-label }}
    name: Custom test command ${{ inputs.description }}
    steps:
      - uses: tenstorrent-metal/metal-workflows/.github/actions/checkout-with-submodule-lfs@v2.0.0
      - name: Set up dyanmic env vars for build
        run: |
          echo "TT_METAL_HOME=$(pwd)" >> $GITHUB_ENV
      - uses: actions/download-artifact@v4
        with:
          name: TTMetal_build_${{ inputs.arch }}
      - name: Extract files
        run: tar -xvf ttm_${{ inputs.arch }}.tar
      - uses: ./.github/actions/install-python-deps
      - name: Run pre/post regression tests in a loop
        run: |
          source ${{ github.workspace }}/python_env/bin/activate
          cd $TT_METAL_HOME
          export PYTHONPATH=$TT_METAL_HOME
          ${{ inputs.command }}
