name: "[internal] TG frequent tests"

on:
  workflow_call:
    inputs:
      os:
        required: false
        type: string
        default: "ubuntu-20.04"

jobs:
  tg-frequent-tests:
    strategy:
      fail-fast: false
      matrix:
        test-group: [
          { name: "TG Llama3 frequent tests", arch: wormhole_b0, model: llama3, timeout: 90, owner_id: U06F3ER8X9A}, # Stuti Raizada
          { name: "TG Llama3-70B (old) frequent tests", arch: wormhole_b0, model: llama3-70b-old, timeout: 90, owner_id: U03FJB5TM5Y}, #Colman Glagovich
          { name: "TG resnet50 frequent tests", arch: wormhole_b0, model: resnet50, timeout: 90, owner_id: U013121KDH9}, # Austin Ho
          { name: "TG unit/distributed frequent tests", arch: wormhole_b0, model: unit, timeout: 90, owner_id: XXXXX}, # Add owner
        ]
    env:
      # TT_METAL_ENV: ${{ vars.TT_METAL_ENV }}
      # ARCH_NAME: ${{ matrix.test-group.arch }}
      LOGURU_LEVEL: INFO
      # LD_LIBRARY_PATH: ${{ github.workspace }}/build/lib
    runs-on:
      # - arch-wormhole_b0
      # - config-tg
      - in-service
      # - bare-metal
      - cloud-virtual-machine
      # - pipeline-functional
    steps:
      - uses: tenstorrent/tt-metal/.github/actions/checkout-with-submodule-lfs@main
      # - name: Set up dynamic env vars for build
        # run: |
          # echo "TT_METAL_HOME=$(pwd)" >> $GITHUB_ENV
      - uses: actions/download-artifact@v4
        with:
          name: eager-dist-${{ inputs.os }}-${{ matrix.test-group.arch }}
          # name: TTMetal_build_${{ matrix.test-group.arch }}
      # - name: Extract files
        # run: tar -xvf ttm_${{ matrix.test-group.arch }}.tar
      # - uses: ./.github/actions/install-python-deps
      - name: Run frequent regression tests
        timeout-minutes: ${{ matrix.test-group.timeout }}
        uses: ./.github/actions/docker-run
        with:
          docker_os_arch: tt-metalium/${{ inputs.os }}-amd64
          install_wheel: true
          docker_password: ${{ secrets.GITHUB_TOKEN }}
          # docker_opts: |
          #   -e ARCH_NAME=${{ matrix.test-group.arch}}
          #   -e TT_METAL_HOME=${{ github.workspace }}
          #   -e LD_LIBRARY_PATH=${{ github.workspace }}/build/lib
          run_args: |
            ./tests/scripts/run_tests.sh --tt-arch wormhole_b0 --pipeline-type frequent_tg_device --dispatch-mode "" --model ${{ matrix.test-group.model }}
      - uses: ./.github/actions/slack-report
        if: ${{ failure() }}
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          owner: ${{ matrix.test-group.owner_id }}
