name: "(TG) TG nightly tests"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 21 * * *"

jobs:
  build-artifact:
    uses: ./.github/workflows/build-artifact.yaml
    secrets: inherit
    with:
      build-wheel: true
  tg-nightly-tests:
    needs: build-artifact
    uses: ./.github/workflows/tg-nightly-tests-impl.yaml
    secrets: inherit
