name: "[internal] UMD Unit tests"

on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      runner-label:
        required: true
        type: string
      timeout:
        required: false
        type: number
        default: 5
      build-artifact:
        required: false
        type: boolean
        default: true

jobs:
  umd-unit-tests:
    name: ${{ inputs.arch }} ${{ inputs.runner-label }}
    runs-on:
      - ${{ inputs.runner-label }}
      - cloud-virtual-machine
      - in-service
    env:
      ARCH_NAME: ${{ inputs.arch }}
      LOGURU_LEVEL: INFO
    steps:
      - uses: tenstorrent-metal/metal-workflows/.github/actions/checkout-with-submodule-lfs@v2.0.0
      - name: Create destination dir for umd artifacts
        run: mkdir _umd
      - uses: actions/download-artifact@v4
        with:
          name: umd_${{ inputs.arch }}
          path: ${{ github.workspace }}/_umd
      - name: Run UMD unit tests
        timeout-minutes: ${{ inputs.timeout }}
        env:
          # Unfortunately need this still, because we don't set any useful rpaths at build time
          LD_LIBRARY_PATH: ${{ github.workspace }}/_umd/lib
        run: |
          ldd _umd/${{ inputs.arch }}/unit_tests
          chmod u+x _umd/${{ inputs.arch }}/unit_tests
          _umd/${{ inputs.arch }}/unit_tests
