name: "[post-commit] UMD Unit Tests"

on:
  workflow_dispatch:

jobs:
  build-umd-artifact:
    uses: ./.github/workflows/build-umd-artifact.yaml
    secrets: inherit
    with:
      build-docker: true
  umd-unit-tests:
    needs: build-artifact
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        test-group: [
          { arch: grayskull, runner-label: E150 },
          { arch: wormhole_b0, runner-label: N150 },
          { arch: wormhole_b0, runner-label: N300 },
        ]
    uses: ./.github/workflows/umd-unit-tests.yaml
    with:
      arch: ${{ matrix.test-group.arch }}
      runner-label: ${{ matrix.test-group.runner-label }}
